### ISSUE TITLE
支持JDK17吗，在JDK17中启动报错应该怎么配置

### ISSUE THREAD

**Issue by zhanxp** [tencentyun/cos-java-sdk-v5#217]
JDK17中已经引入了依赖，但是启动报错找不到类；也已经增加了 --add-opens java.base/java.lang=ALL-UNNAMED
--add-opens java.base/java.util=ALL-UNNAMED 参数。

Caused by: java.lang.NoClassDefFoundError: com/qcloud/cos/COS
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3402)
	at java.base/java.lang.Class.getDeclaredMethods(Class.java:2504)
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:465)
	... 21 common frames omitted
Caused by: java.lang.ClassNotFoundException: com.qcloud.cos.COS
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 25 common frames omitted

**Comment by paakciu** [comment]
同样遇到这个问题了
