### ISSUE TITLE
跨园区拷贝, 即将一个园区的文件拷贝到另一个园区：失败

### ISSUE THREAD

**Issue by hexingjiehao** [tencentyun/cos-java-sdk-v5#22]
版本5.5.1
调用其中的跨园区拷贝代码，TransferManagerDemo.java中的copyFileForDiffRegion方法。
报错显示：
com.qcloud.cos.exception.CosServiceException: Not Found (Status Code: 404; Error Code: 404 Not Found; Request ID: NWNhNDUzNGFfOTcxYzBiMDlfNjNhZl84YjVlMmY=); Trace ID: OGVmYzZiMmQzYjA2OWNhODk0NTRkMTBiOWVmMDAxODc0OWRkZjk0ZDM1NmI1M2E2MTRlY2MzZDhmNmI5MWI1OTBjYzE2MjAxN2M1MzJiOTdkZjMxMDVlYTZjN2FiMmI0NTI1ZGFjMGQ1ZjQwZmYyN2NjODNmNzJiYzQwMmUyYTY=
	at com.qcloud.cos.http.DefaultCosHttpClient.handlerErrorMessage(DefaultCosHttpClient.java:302)
	at com.qcloud.cos.http.DefaultCosHttpClient.exeute(DefaultCosHttpClient.java:402)
	at com.qcloud.cos.COSClient.invoke(COSClient.java:524)
	at com.qcloud.cos.COSClient.getObjectMetadata(COSClient.java:1088)
	at com.qcloud.cos.transfer.TransferManager.copy(TransferManager.java:1399)
	at com.xiongjie.Application.haha(Application.java:722)
	at com.xiongjie.Application.main(Application.java:67)

**Comment by liuyongqing** [comment]
在copy之前，java sdk需要head一下源对象的相关信息，以决定使用PUTObjectCopy或分块拷贝；该报错，应该是源对象不存在，所以404，可以检查bucket、地域等信息
