### ISSUE TITLE
Connection pool shut down

### ISSUE THREAD

**Issue by sanyecao2314** [tencentyun/cos-java-sdk-v5#71]
25升级到28后,运行一天左右.就会大面积报下面的错误

```
com.qcloud.cos.exception.CosClientException: httpClient execute occur a unknow exception, httpRequest: endpoint: xxx-123456.cos.ap-shanghai.myqcloud.com, resourcepath: /projects/A__2020-03/project_5e67509360b2bcd915725ae9/task_5f27742a60b223ab27ac5b42/, httpMethod: HEAD, headers { Authorization : q-sign-algorithm=sha1&q-ak=sssss&q-sign-time=1596589498;1596593098&q-key-time=1596589498;1596593098&q-header-list=host&q-url-param-list=&q-signature=4d66cb9db906caa2f4c4711bb624d0afb6dc7513, User-Agent : cos-java-sdk-v5.6.28/Linux/jdk-1.8.0_151/Java HotSpot(TM) 64-Bit Server VM, Host : xxx-123456.cos.ap-shanghai.myqcloud.com, }, params: { }

	at com.qcloud.cos.http.DefaultCosHttpClient.exeute(DefaultCosHttpClient.java:501)
	at com.qcloud.cos.COSClient.invoke(COSClient.java:601)
	at com.qcloud.cos.COSClient.getObjectMetadata(COSClient.java:1211)
	at com.qcloud.cos.COSClient.getObjectMetadata(COSClient.java:1188)
	at com.qcloud.cos.COSClient.doesObjectExist(COSClient.java:1175)
	at java.lang.Thread.run(Thread.java:748)

Caused by: java.lang.IllegalStateException: Connection pool shut down
	at org.apache.http.util.Asserts.check(Asserts.java:34)
	at org.apache.http.pool.AbstractConnPool.lease(AbstractConnPool.java:184)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.requestConnection(PoolingHttpClientConnectionManager.java:251)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:175)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at com.qcloud.cos.http.DefaultCosHttpClient.executeOneRequest(DefaultCosHttpClient.java:414)
	at com.qcloud.cos.http.DefaultCosHttpClient.exeute(DefaultCosHttpClient.java:475)
	... 22 more
```

**Comment by liuyongqing** [comment]
@sanyecao2314 ，您好，请问您这边存在shudown后继续使用cosclient的情况吗？

**Comment by sanyecao2314** [comment]
我的cosclient是静态单例一直用的.代码里就没有调过shudown方法.

**Comment by liuyongqing** [comment]
@sanyecao2314 ，您好，
![image](https://user-images.githubusercontent.com/5205797/98521423-5f181600-22ae-11eb-81d3-a50d6c4407b0.png)，这里根据httpclient源码分析，是调用了连接池的shutdown方法后抛出的，连接池关闭有几种可能，一种是主动关闭，另外中断了空闲连接回收线程，也会关闭连接池，
如果您仍然存在该问题，可提腾讯云工单，一起排查该问题。
